### ISSUE TITLE
Bot stuck for long periods of time waiting to buy

### ISSUE THREAD

**Issue by ghost** [ccxt/binance-trade-bot#227] opened 2021-03-22 18:57 UTC
When the bot sells a coin, sometimes it hangs for long periods of time to buy the next coin because the price increased on the new coin. Instead of waiting for hours and/or days, perhaps the bot could cancel the buy request and look for a new coin to buy.

This would make the bot more active and less prone to sitting on the sidelines waiting for the price to drop.

**Comment by rel-s** [comment] 2021-03-22 18:59
We are aware of this issue - it is actually a duplicate of other issues here, and we have plans (and pending PRs) to fix this. Thanks!

**Closed as completed by rel-s** 2021-03-22 18:59 UTC
