### ISSUE TITLE
Bot stuck at buying

### ISSUE THREAD

**Issue by HyperSound** [ccxt/binance-trade-bot#152] opened 2021-02-28 21:47 UTC
The bot gets stuck at the buying process if the coin prize raises. This means that the open order doesnt get  filled. Can you put a cooldown on the filling so that it skips the order and cancels it after an certain amount of time? Thanks

**Comment by exter01** [comment] 2021-02-28 22:03
I have same problem...

**Comment by ntamas94** [comment] 2021-03-01 04:09
Same misses 0.00001 TUSD

**Comment by johannes-peeters** [comment] 2021-03-01 08:46
Duplicate of #72

**Comment by rel-s** [comment] 2021-03-01 08:47
Yep, we want to take care of this eventually but it really isn't as straightforward as adding a timer. You guys are welcome to join the discussion on #72, or our Discord channel.

**Closed as completed by rel-s** 2021-03-01 08:47 UTC
