### ISSUE TITLE
Too much request weight used

### ISSUE THREAD

**Issue by heliohead** [ccxt/binance-trade-bot#105] opened 2021-02-21 00:12 UTC
Hi, i have no experience with python to contribute, but i will learn 😄 

APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.
 
  2021-02-20 13:38:56,900 - crypto_trader_logger - INFO - Error while scouting...
  APIError(code=-1003): Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API.

**Comment by remriel** [comment] 2021-02-21 19:56
Binance has an API limit. 

> At the current time Binance rate limits are:
> 
> 1200 requests per minute
> 10 orders per second
> 100,000 orders per 24hrs

https://python-binance.readthedocs.io/en/latest/overview.html#:~:text=API%20Rate%20Limit,-Check%20the%20get_exchange_info&text=At%20the%20current%20time%20Binance,100%2C000%20orders%20per%2024hrs

**Comment by edeng23** [comment] 2021-02-22 00:28
I'll have to see a more of the log to work out what happened.

**Comment by heliohead** [comment] 2021-02-22 20:17
the whole log is on a gist 
https://gist.github.com/heliohead/ac389830f227db057f005a71f13af0de

**Comment by rel-s** [comment] 2021-02-23 10:46
This seems to be a duplicate of #66 - the infinite loop bug causes you to send many api messages. Regardless of this issue, we should move to a websocket implementation- a separate issue will be opened for this.
For more Support see the issue I referenced, and consult our Discord channel.

**Closed as completed by rel-s** 2021-02-23 10:46 UTC

**Comment by danstis** [comment] 2021-03-23 00:53
@rel-s I don't think this is related to #66 as it happens on a fresh setup running the code from master. 
It seems to be related to the new fee lookup, as it starts happening from that commit I believe. I'll do a bisect to see if I can find the commit that it started on.

I notice that the scouting became very slow (~1sec per coin) at the same time. 
I have tested with a reduced coins list, as well as an increased scouting interval. Both made a the issue occur less frequently, but do not completely fix the issue.

I expect that PR #211 will fix this issue when it's merged. From my observations it seems that master is currently broken until it's merged.

**Comment by xioxu** [comment] 2021-03-23 03:30
Hi, I had even increase "scout_sleep_time " to "75" , but the issue still happen.

**Comment by danstis** [comment] 2021-03-23 04:10
I should have added that this is not *only* related to #66, I agree that #66 will also cause this behaviour due to the infinite loop of failures. This is also a symptom when using the current master without having failures to buy/sell.
