### ISSUE TITLE
OSError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by iiiyu** [ccxt/binance-trade-bot#131] opened 2021-02-25 21:23 UTC
```
2021-02-25 20:10:17,509 - crypto_trader_logger - INFO - Error while scouting...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 597, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1322, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 309, in recv_into
    return self.recv_into(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 299, in recv_into
    raise SocketError(str(e))
OSError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

```

I found this url 
https://github.com/sammchardy/python-binance/issues/389

Have any ideas?
 
https://github.com/edeng23/binance-trade-bot/issues/118

Maybe switch API can solve this problem?

**Comment by rel-s** [comment] 2021-02-25 21:27
This issue is out of scope, as this is not a bug in the bot. The connection may reset, and as written in the link you provided, it very well may be a problem on Binance's side. Further discussion around this issue should take place in our Discord channel (link in README).

**Closed as completed by rel-s** 2021-02-25 21:27 UTC
